### ISSUE TITLE
[Passive Gas Vent][Enhancement] Add support for increased pipe capacity

### ISSUE THREAD

**Issue by andr9528** [ihoromi4/ONIMods#12]
## Description
Using a mod like [Customize Buildings](https://steamcommunity.com/sharedfiles/filedetails/?id=1818138009) it is possible to increase the maximum gas transfered per package in a pipe to just about any amount the player wants. With the use of that mod i am currently increasing my capacity by 10x.

However this increase does not translate into the Passive gas vent being able to draw out more gas from a tile, whose gas pressure is sufficently high. It would be cool if the mod added support for increased gas pipe capacity, via one of the two suggested changes below, or any other suitable way you find.

## Option one - The Simple Solution

Set the maximum gas a Gas Vent Input can draw out to be equal to the max presure of a gas pipe.

## Option two - The Advanced Solution

Alter the current one to only do up to 50% of pipe capacity, along with removing the ablity to enable/disable via automation.

Then add an advanced version, which also requires some plastic, or similar higher tier resource. This Advanced version would do up to 100%, and be able to be controlled via automation, like the current one.

Perhabs the basic one also draws in gas slower compared to the advanced one, requireing a higher pressure to achieve the same output as an advanced version.

## Final Thoughs

Hope you like this suggestion. 

Currently the build i use for supplying my Atmo Suits with oxygen from my infinite storage is only limited by the speed that the 3 passive gas vents used, draw gas out. I had hoped increasing the capacity would have already worked, with how the amount of gas from the passive gas vent dynamically changes, but sadly it doesn't.

**Comment by ihoromi4** [comment]
Mod settings was added. You can now set as high Ven gas consumption rate as You like.
