### ISSUE TITLE
Configuration file suggestion

### ISSUE THREAD

**Issue by DanteyPL** [ihoromi4/ONIMods#7]
## Suggestion
Can you expose configuration data to external json file? This could give more customization for mod.
It can also have more options for building behavior.

## Expected Behavior
Mod will create config JSON file at first mod load. Every load of game it would fetch configuration data from JSON file. 

## Actual Behavior
Mod have hardcoded behavior, that cannot be changed.

**Comment by ihoromi4** [comment]
Mod settings was added.
