### ISSUE TITLE
Latest version causing crash on startup

### ISSUE THREAD

**Issue by PlaidPiper** [ihoromi4/ONIMods#9]
Error output below:

NullReferenceException: Object reference not set to an instance of an object

PassiveGasVentInput.Utils.Localize (System.Type root) (at <9e2c2feb46bc495393b86fa90b1ebcc1>:0)
PassiveGasVentInput.PassiveGasVentInputPatch+StringLocalisationPatch.Postfix () (at <9e2c2feb46bc495393b86fa90b1ebcc1>:0)
(wrapper dynamic-method) Localization.Localization.Initialize_Patch1()
Global.Awake () (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/Global.cs:432)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion, Transform)
Util:KInstantiate(GameObject, Vector3, Quaternion, GameObject, String, Boolean, Int32) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/Util.cs:226)
Util:KInstantiate(GameObject, GameObject, String) (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/Plugins/Klei/util/Util.cs:198)
LaunchInitializer:Update() (at C:/jenkins_workspace/workspace/SimGame_Windows/game/Assets/scripts/game/LaunchInitializer.cs:67)

Build: 469473

**Comment by ihoromi4** [comment]
Fixed
